[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"pallets/*",
	"runtime",
]

resolver = "2"

[patch.crates-io]
ss58-registry = { git = "https://github.com/paritytech/ss58-registry" }
