name: Checks & Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup for checks
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler

    - name: Build
      run: cargo build --verbose
  
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup for checks
        run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Run clippy
        run: cargo clippy -- -D warnings
  
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run cargofmt
        run: cargo fmt --all -- --check
